### ISSUE TITLE
[Bug] ModuleNotFoundError: No module named 'send2trash.plat_other'

### ISSUE THREAD

**Issue by vanchaxy** [jlesage/docker-dupeguru#19]
### Current Behavior

Trying to start the container. See the logs below.

v23.06.1, staring as kubernetes deployment

### Container creation

```apiVersion: apps/v1
kind: Deployment
metadata:
  name: dupeguru
  labels:
    app.kubernetes.io/instance: dupeguru
    app.kubernetes.io/name: dupeguru
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: dupeguru
      app.kubernetes.io/name: dupeguru
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: dupeguru
        app.kubernetes.io/name: dupeguru
    spec:
      containers:
        - image: {{ .Values.dupeguru.image.repository }}:{{ .Values.dupeguru.image.tag }}
          imagePullPolicy: {{ .Values.dupeguru.image.imagePullPolicy }}
          name: dupeguru
          ports:
            - containerPort: 5800
              protocol: TCP
              name: dupeguru
          volumeMounts:
            - name: library
              mountPath: /library
      volumes:
        - name: library
          persistentVolumeClaim:
            claimName: photo-library
```

### Container log

```text
[init        ] container is starting...
[cont-env    ] loading container environment variables...
[cont-env    ] APP_NAME: loading...
[cont-env    ] APP_VERSION: loading...
[cont-env    ] DISPLAY: executing...
[cont-env    ] DISPLAY: terminated successfully.
[cont-env    ] DISPLAY: loading...
[cont-env    ] DOCKER_IMAGE_PLATFORM: loading...
[cont-env    ] DOCKER_IMAGE_VERSION: loading...
[cont-env    ] GTK2_RC_FILES: executing...
[cont-env    ] GTK2_RC_FILES: terminated successfully.
[cont-env    ] GTK2_RC_FILES: loading...
[cont-env    ] GTK_THEME: executing...
[cont-env    ] GTK_THEME: terminated successfully.
[cont-env    ] GTK_THEME: loading...
[cont-env    ] HOME: loading...
[cont-env    ] QT_STYLE_OVERRIDE: executing...
[cont-env    ] QT_STYLE_OVERRIDE: terminated successfully.
[cont-env    ] QT_STYLE_OVERRIDE: loading...
[cont-env    ] TAKE_CONFIG_OWNERSHIP: loading...
[cont-env    ] TRASH_DIR: loading...
[cont-env    ] XDG_CACHE_HOME: loading...
[cont-env    ] XDG_CONFIG_HOME: loading...
[cont-env    ] XDG_DATA_HOME: loading...
[cont-env    ] XDG_RUNTIME_DIR: loading...
[cont-env    ] XDG_STATE_HOME: loading...
[cont-env    ] container environment variables initialized.
[cont-secrets] loading container secrets...
[cont-secrets] container secrets loaded.
[cont-init   ] executing container initialization scripts...
[cont-init   ] 10-certs.sh: executing...
[cont-init   ] 10-certs.sh: terminated successfully.
[cont-init   ] 10-check-app-niceness.sh: executing...
[cont-init   ] 10-check-app-niceness.sh: terminated successfully.
[cont-init   ] 10-cjk-font.sh: executing...
[cont-init   ] 10-cjk-font.sh: terminated successfully.
[cont-init   ] 10-clean-logmonitor-states.sh: executing...
[cont-init   ] 10-clean-logmonitor-states.sh: terminated successfully.
[cont-init   ] 10-clean-tmp-dir.sh: executing...
[cont-init   ] 10-clean-tmp-dir.sh: terminated successfully.
[cont-init   ] 10-fontconfig-cache-dir.sh: executing...
[cont-init   ] 10-fontconfig-cache-dir.sh: terminated successfully.
[cont-init   ] 10-init-users.sh: executing...
[cont-init   ] 10-init-users.sh: terminated successfully.
[cont-init   ] 10-nginx.sh: executing...
[cont-init   ] 10-nginx.sh: terminated successfully.
[cont-init   ] 10-openbox.sh: executing...
[cont-init   ] 10-openbox.sh: terminated successfully.
[cont-init   ] 10-set-tmp-dir-perms.sh: executing...
[cont-init   ] 10-set-tmp-dir-perms.sh: terminated successfully.
[cont-init   ] 10-vnc-password.sh: executing...
[cont-init   ] 10-vnc-password.sh: terminated successfully.
[cont-init   ] 10-web-data.sh: executing...
[cont-init   ] 10-web-data.sh: terminated successfully.
[cont-init   ] 10-x11-unix.sh: executing...
[cont-init   ] 10-x11-unix.sh: terminated successfully.
[cont-init   ] 10-xdg-runtime-dir.sh: executing...
[cont-init   ] 10-xdg-runtime-dir.sh: terminated successfully.
[cont-init   ] 15-install-pkgs.sh: executing...
[cont-init   ] 15-install-pkgs.sh: terminated successfully.
[cont-init   ] 55-dupeguru.sh: executing...
[cont-init   ] 55-dupeguru.sh: '/defaults/dupeGuru.conf' -> '/config/xdg/config/Hardcoded Software/dupeGuru.conf'
[cont-init   ] 55-dupeguru.sh: '/defaults/QtProject.conf' -> '/config/xdg/config/QtProject.conf'
[cont-init   ] 55-dupeguru.sh: terminated successfully.
[cont-init   ] 85-take-config-ownership.sh: executing...
[cont-init   ] 85-take-config-ownership.sh: terminated successfully.
[cont-init   ] 89-info.sh: executing...
    ╭――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――╮
    │                                                                      │
    │ Application:           dupeGuru                                      │
    │ Application Version:   4.3.1                                         │
    │ Docker Image Version:  23.06.1                                       │
    │ Docker Image Platform: linux/amd64                                   │
    │                                                                      │
    ╰――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――╯
[cont-init   ] 89-info.sh: terminated successfully.
[cont-init   ] all container initialization scripts executed.
[init        ] giving control to process supervisor.
[supervisor  ] loading services...
[supervisor  ] loading service 'default'...
[supervisor  ] loading service 'logrotate'...
[supervisor  ] loading service 'logmonitor'...
[supervisor  ] service 'logmonitor' is disabled.
[supervisor  ] loading service 'app'...
[supervisor  ] loading service 'gui'...
[supervisor  ] loading service 'xvnc'...
[supervisor  ] loading service 'nginx'...
[supervisor  ] loading service 'certsmonitor'...
[supervisor  ] service 'certsmonitor' is disabled.
[supervisor  ] loading service 'openbox'...
[supervisor  ] all services loaded.
[supervisor  ] starting services...
[supervisor  ] starting service 'xvnc'...
[xvnc        ] Xvnc TigerVNC 1.13.1 - built May 16 2023 17:43:49
[xvnc        ] Copyright (C) 1999-2022 TigerVNC Team and many others (see README.rst)
[xvnc        ] See https://www.tigervnc.org for information on TigerVNC.
[xvnc        ] Underlying X server release 12014000
[xvnc        ] Wed Aug 16 18:16:23 2023
[xvnc        ]  vncext:      VNC extension running!
[xvnc        ]  vncext:      Listening for VNC connections on /tmp/vnc.sock (mode 0660)
[xvnc        ]  vncext:      Listening for VNC connections on all interface(s), port 5900
[xvnc        ]  vncext:      created VNC server for screen 0
[supervisor  ] starting service 'nginx'...
[nginx       ] Listening for HTTP connections on port 5800.
[supervisor  ] starting service 'openbox'...
[supervisor  ] starting service 'app'...
[supervisor  ] all services started.
[app         ] Traceback (most recent call last):
[app         ]   File "/usr/share/dupeguru/send2trash/__init__.py", line 26, in <module>
[app         ]     from .plat_gio import send2trash
[app         ] ModuleNotFoundError: No module named 'send2trash.plat_gio'
[app         ] During handling of the above exception, another exception occurred:
[app         ] Traceback (most recent call last):
[app         ]   File "/usr/bin/dupeguru", line 88, in <module>
[app         ]     sys.exit(main())
[app         ]   File "/usr/bin/dupeguru", line 71, in main
[app         ]     from qt.app import DupeGuru
[app         ]   File "/usr/share/dupeguru/qt/app.py", line 22, in <module>
[app         ]     from core.app import AppMode, DupeGuru as DupeGuruModel
[app         ]   File "/usr/share/dupeguru/core/app.py", line 17, in <module>
[app         ]     from send2trash import send2trash
[app         ]   File "/usr/share/dupeguru/send2trash/__init__.py", line 29, in <module>
[app         ]     from .plat_other import send2trash
[app         ] ModuleNotFoundError: No module named 'send2trash.plat_other'
[supervisor  ] service 'app' exited (with status 1).
[supervisor  ] service 'app' exited, shutting down...
[supervisor  ] stopping service 'openbox'...
[supervisor  ] service 'openbox' exited (with status 0).
[supervisor  ] stopping service 'nginx'...
[supervisor  ] service 'nginx' exited (with status 0).
[supervisor  ] stopping service 'xvnc'...
[xvnc        ] Wed Aug 16 18:16:26 2023
[xvnc        ]  ComparingUpdateTracker: 0 pixels in / 0 pixels out
[xvnc        ]  ComparingUpdateTracker: (1:-nan ratio)
[supervisor  ] service 'xvnc' exited (with status 0).
[finish      ] executing container finish scripts...
[finish      ] all container finish scripts executed.
```

**Comment by vanchaxy** [comment]
https://github.com/jlesage/docker-dupeguru/blob/ffc109d19d29a4aeb82a806376507274a09528a8/rootfs/usr/share/dupeguru/send2trash/__init__.py#L13
I think we need to also detect `containerd.service` in `/proc/self/cgroup`. Example cgroup:

```12:devices:/system.slice/containerd.service/kubepods-besteffort-podd7a580a8_466e_418b_81b3_9883cf7fa8b0.slice:cri-containerd:4245ae38ec2682bef29c4097bfbef6b0fc2562f744077d842bf1b0d6273ad610
11:perf_event:/kubepods-besteffort-podd7a580a8_466e_418b_81b3_9883cf7fa8b0.slice:cri-containerd:4245ae38ec2682bef29c4097bfbef6b0fc2562f744077d842bf1b0d6273ad610
10:pids:/system.slice/containerd.service/kubepods-besteffort-podd7a580a8_466e_418b_81b3_9883cf7fa8b0.slice:cri-containerd:4245ae38ec2682bef29c4097bfbef6b0fc2562f744077d842bf1b0d6273ad610
9:freezer:/kubepods-besteffort-podd7a580a8_466e_418b_81b3_9883cf7fa8b0.slice:cri-containerd:4245ae38ec2682bef29c4097bfbef6b0fc2562f744077d842bf1b0d6273ad610
8:cpuset:/kubepods-besteffort-podd7a580a8_466e_418b_81b3_9883cf7fa8b0.slice:cri-containerd:4245ae38ec2682bef29c4097bfbef6b0fc2562f744077d842bf1b0d6273ad610
7:hugetlb:/kubepods-besteffort-podd7a580a8_466e_418b_81b3_9883cf7fa8b0.slice:cri-containerd:4245ae38ec2682bef29c4097bfbef6b0fc2562f744077d842bf1b0d6273ad610
6:blkio:/system.slice/containerd.service/kubepods-besteffort-podd7a580a8_466e_418b_81b3_9883cf7fa8b0.slice:cri-containerd:4245ae38ec2682bef29c4097bfbef6b0fc2562f744077d842bf1b0d6273ad610
5:rdma:/kubepods-besteffort-podd7a580a8_466e_418b_81b3_9883cf7fa8b0.slice:cri-containerd:4245ae38ec2682bef29c4097bfbef6b0fc2562f744077d842bf1b0d6273ad610
4:net_cls,net_prio:/kubepods-besteffort-podd7a580a8_466e_418b_81b3_9883cf7fa8b0.slice:cri-containerd:4245ae38ec2682bef29c4097bfbef6b0fc2562f744077d842bf1b0d6273ad610
3:memory:/system.slice/containerd.service/kubepods-besteffort-podd7a580a8_466e_418b_81b3_9883cf7fa8b0.slice:cri-containerd:4245ae38ec2682bef29c4097bfbef6b0fc2562f744077d842bf1b0d6273ad610
2:cpu,cpuacct:/system.slice/containerd.service/kubepods-besteffort-podd7a580a8_466e_418b_81b3_9883cf7fa8b0.slice:cri-containerd:4245ae38ec2682bef29c4097bfbef6b0fc2562f744077d842bf1b0d6273ad610
1:name=systemd:/system.slice/containerd.service/kubepods-besteffort-podd7a580a8_466e_418b_81b3_9883cf7fa8b0.slice:cri-containerd:4245ae38ec2682bef29c4097bfbef6b0fc2562f744077d842bf1b0d6273ad610
0::/kubepods-besteffort-podd7a580a8_466e_418b_81b3_9883cf7fa8b0.slice:cri-containerd:4245ae38ec2682bef29c4097bfbef6b0fc2562f744077d842bf1b0d6273ad610
```

**Comment by vanchaxy** [comment]
Fixed by mounting emptyDir at /.dockerenv. But still would be nice to detect containerd env.

```
          volumeMounts:
            - name: dockerenv
              mountPath: /.dockerenv
      volumes:
        - name: dockerenv
          emptyDir: {}
```

**Comment by jlesage** [comment]
Thank you, this is now fixed with the latest image.
