### ISSUE TITLE
No module named 'send2trash.plat_other'

### ISSUE THREAD

**Issue by KaiDevrim** [jlesage/docker-dupeguru#9]
I run the app in my docker-compose.yaml file like so:
```docker
dupeguru:
      container_name: dupeguru
      restart: unless-stopped
      ports:
          - '5800:5800'
      volumes:
          - './data/dupeguru:/config:rw'
          - '/mnt/Luffy:/storage:rw'
      image: jlesage/dupeguru
```

and it keeps dying with the error code:

```txt
[services.d] starting logmonitor...
[logmonitor] no file to monitor: disabling service...
[services.d] starting app...
[app] starting dupeGuru...
[services.d] done.
Traceback (most recent call last):
  File "/usr/share/dupeguru/send2trash/__init__.py", line 27, in <module>
    from .plat_gio import send2trash
ModuleNotFoundError: No module named 'send2trash.plat_gio'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/dupeguru", line 89, in <module>
    sys.exit(main())
  File "/usr/bin/dupeguru", line 72, in main
    from qt.app import DupeGuru
  File "/usr/share/dupeguru/qt/app.py", line 22, in <module>
    from core.app import AppMode, DupeGuru as DupeGuruModel
  File "/usr/share/dupeguru/core/app.py", line 14, in <module>
    from send2trash import send2trash
  File "/usr/share/dupeguru/send2trash/__init__.py", line 30, in <module>
    from .plat_other import send2trash
ModuleNotFoundError: No module named 'send2trash.plat_other'
[services.d] stopping services
[services.d] stopping app...
[services.d] stopping logmonitor...
[services.d] stopping openbox...
[services.d] stopping x11vnc...
caught signal: 15
16/08/2021 04:17:07 deleted 40 tile_row polling images.
[services.d] stopping statusmonitor...
[services.d] stopping xvfb...
[services.d] stopping nginx...
[services.d] stopping certsmonitor...
[services.d] stopping s6-fdholderd...
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by tacotran** [comment]
I have the same issue, did you find a fix?

**Comment by tacotran** [comment]
I took a closer look and think I figured out the issue, or at least kind of did.

This function here: https://github.com/jlesage/docker-dupeguru/blob/ffc109d19d29a4aeb82a806376507274a09528a8/rootfs/usr/share/dupeguru/send2trash/__init__.py#L9
 is expecting a certain format, maybe something like below

```
$ more /proc/self/cgroup
14:name=systemd:/docker/7be92808767a667f35c8505cbf40d14e931ef6db5b0210329cf193b15ba9d605
13:pids:/docker/7be92808767a667f35c8505cbf40d14e931ef6db5b0210329cf193b15ba9d605
12:hugetlb:/docker/7be92808767a667f35c8505cbf40d14e931ef6db5b0210329cf193b15ba9d605
11:net_prio:/docker/7be92808767a667f35c8505cbf40d14e931ef6db5b0210329cf193b15ba9d605
10:perf_event:/docker/7be92808767a667f35c8505cbf40d14e931ef6db5b0210329cf193b15ba9d605
9:net_cls:/docker/7be92808767a667f35c8505cbf40d14e931ef6db5b0210329cf193b15ba9d605
8:freezer:/docker/7be92808767a667f35c8505cbf40d14e931ef6db5b0210329cf193b15ba9d605
7:devices:/docker/7be92808767a667f35c8505cbf40d14e931ef6db5b0210329cf193b15ba9d605
6:memory:/docker/7be92808767a667f35c8505cbf40d14e931ef6db5b0210329cf193b15ba9d605
5:blkio:/docker/7be92808767a667f35c8505cbf40d14e931ef6db5b0210329cf193b15ba9d605
4:cpuacct:/docker/7be92808767a667f35c8505cbf40d14e931ef6db5b0210329cf193b15ba9d605
3:cpu:/docker/7be92808767a667f35c8505cbf40d14e931ef6db5b0210329cf193b15ba9d605
2:cpuset:/docker/7be92808767a667f35c8505cbf40d14e931ef6db5b0210329cf193b15ba9d605
1:name=openrc:/docker
```

Instead mine looks like

```
11:net_prio,net_cls:/system.slice/docker-d34666dd740f532f67c0a7fe83e0da7a8d900a6e2812b353e99c5b0258920f34.scope
10:perf_event:/system.slice/docker-d34666dd740f532f67c0a7fe83e0da7a8d900a6e2812b353e99c5b0258920f34.scope
9:hugetlb:/system.slice/docker-d34666dd740f532f67c0a7fe83e0da7a8d900a6e2812b353e99c5b0258920f34.scope
8:cpuset:/system.slice/docker-d34666dd740f532f67c0a7fe83e0da7a8d900a6e2812b353e99c5b0258920f34.scope
7:cpuacct,cpu:/system.slice/docker-d34666dd740f532f67c0a7fe83e0da7a8d900a6e2812b353e99c5b0258920f34.scope
6:devices:/system.slice/docker-d34666dd740f532f67c0a7fe83e0da7a8d900a6e2812b353e99c5b0258920f34.scope
5:blkio:/system.slice/docker-d34666dd740f532f67c0a7fe83e0da7a8d900a6e2812b353e99c5b0258920f34.scope
4:pids:/system.slice/docker-d34666dd740f532f67c0a7fe83e0da7a8d900a6e2812b353e99c5b0258920f34.scope
3:freezer:/system.slice/docker-d34666dd740f532f67c0a7fe83e0da7a8d900a6e2812b353e99c5b0258920f34.scope
2:memory:/system.slice/docker-d34666dd740f532f67c0a7fe83e0da7a8d900a6e2812b353e99c5b0258920f34.scope
1:name=systemd:/system.slice/docker-d34666dd740f532f67c0a7fe83e0da7a8d900a6e2812b353e99c5b0258920f34.scope
```

And since the only file included is plat.docker none of the other imports work. I 'fixed' this by hardcoding the import and mounting __init__.py over the one included with the container.

**Comment by jlesage** [comment]
Thanks for pointing this.  The docker detection needs to be updated to better work in all environments.  I will fix that!

**Comment by jlesage** [comment]
Please try the latest image, which should fix this issue.
